// Canonical examples, language-pattern inspirations, and app-like fixtures.
export const expandedCorpus = [
  {"id":"partial-application","path":"patterns/partial_application.ass","name":"main","args":[7],"expected":17,"inspiration":"ML/Haskell currying"},
  {"id":"function-composition","path":"patterns/function_composition.ass","name":"main","args":[4],"expected":25,"inspiration":"Haskell composition","libraries":["../lib/patterns.ass"]},
  {"id":"nested-products","path":"patterns/nested_products.ass","name":"main","args":[3],"expected":50,"inspiration":"ML destructuring"},
  {"id":"record-lens","path":"patterns/record_lens.ass","name":"main","args":[10],"expected":{"score":15,"active":true},"inspiration":"functional lenses","libraries":["../lib/patterns.ass"]},
  {"id":"option-map","path":"patterns/option_map.ass","name":"main","args":[3,true],"expected":9,"inspiration":"Rust Option / ML Maybe encoded as a record","libraries":["../lib/patterns.ass"]},
  {"id":"result-validation","path":"patterns/result_validation.ass","name":"main","args":[5,2],"expected":{"ok":true,"code":0,"value":250},"inspiration":"Rust Result-style explicit error values","libraries":["../lib/patterns.ass"]},
  {"id":"reader-configuration","path":"patterns/reader_configuration.ass","name":"main","args":[2,3],"expected":49,"inspiration":"Reader-style dependency injection","libraries":["../lib/patterns.ass"]},
  {"id":"strategy-dictionary","path":"patterns/strategy_dictionary.ass","name":"main","args":[[2,3,4]],"expected":{"total":9,"product":24},"inspiration":"typeclass/trait dictionary passing; statically staged"},
  {"id":"predicate-algebra","path":"patterns/predicate_algebra.ass","name":"main","args":[[-2,0,2,9,20]],"expected":2,"inspiration":"composable predicates","libraries":["../lib/patterns.ass"]},
  {"id":"church-choice","path":"patterns/church_choice.ass","name":"main","args":[4],"expected":5,"inspiration":"lambda-calculus Church encodings; static functions"},
  {"id":"church-numeral","path":"patterns/church_numeral.ass","name":"main","args":[1],"expected":7,"inspiration":"Church numeral as staged iteration"},
  {"id":"state-passing","path":"patterns/state_passing.ass","name":"main","args":[10],"expected":{"state":15,"first":10,"second":12},"inspiration":"explicit state-passing style"},
  {"id":"newtype-convention","path":"patterns/newtype_convention.ass","name":"main","args":[4],"expected":{"meters":6},"inspiration":"unit wrappers; structural rather than nominal types"},
  {"id":"complex-numbers","path":"patterns/complex_numbers.ass","name":"main","args":[1],"expected":{"real":-5,"imag":10},"inspiration":"record-based complex arithmetic"},
  {"id":"dual-autodiff","path":"patterns/dual_autodiff.ass","name":"main","args":[3],"expected":{"value":27,"derivative":27},"inspiration":"forward-mode dual-number differentiation"},
  {"id":"matrix-transform","path":"patterns/matrix_transform.ass","name":"main","args":[2],"expected":{"_0":8,"_1":10},"inspiration":"fixed-size matrix products via tuple values"},
  {"id":"bounded-while","path":"patterns/bounded_while.ass","name":"main","args":[10],"expected":{"state":16,"steps":4,"done":true},"inspiration":"while-loop variant with explicit work budget"},
  {"id":"generator-every-other","path":"patterns/generator_every_other.ass","name":"main","args":[[1,2,3,4,5]],"expected":[1,3,5],"inspiration":"generator-style state machine; at most one output per input"},
  {"id":"enumerated-map","path":"patterns/enumerated_map.ass","name":"main","args":[[10,20,30]],"expected":[10,21,32],"inspiration":"Python enumerate / Rust enumerate via checked positional pairing"},
  {"id":"filter-map-pipeline","path":"patterns/filter_map_pipeline.ass","name":"main","args":[[-3,2,4]],"expected":20,"inspiration":"iterator pipelines / SQL WHERE plus aggregate"},
  {"id":"take-while-fold","path":"patterns/take_while_fold.ass","name":"main","args":[[1,2,-1,99]],"expected":{"state":3,"steps":3,"done":true},"inspiration":"take-while aggregate variant; stopping event is visited"},
  {"id":"runtime-contract","path":"patterns/runtime_contract.ass","name":"main","args":[[2,4],2],"expected":[1,2],"inspiration":"design-by-contract with explicit trap"},
  {"id":"lazy-default","path":"patterns/lazy_default.ass","name":"main","args":[[]],"expected":42,"inspiration":"lazy optional/default selection"},
  {"id":"polymorphic-identity","path":"patterns/polymorphic_identity.ass","name":"main","args":[5],"expected":{"number":5,"flag":true,"pair":{"_0":5,"_1":false}},"inspiration":"let-polymorphic reuse","libraries":["../lib/patterns.ass"]},
  {"id":"closure-factory","path":"patterns/closure_factory.ass","name":"main","args":[[1,2,3]],"expected":[5,7,9],"inspiration":"capturing closure factory, erased before runtime"},
  {"id":"record-update","path":"patterns/record_update.ass","name":"main","args":["demo"],"expected":{"name":"demo","score":9,"enabled":true},"inspiration":"immutable record update written explicitly"},
  {"id":"fsm-traffic-light","path":"patterns/fsm_traffic_light.ass","name":"main","args":[[1,1,1,1,1]],"expected":[1,2,0,1,2],"inspiration":"finite state machine with numeric tags"},
  {"id":"histogram-three-bins","path":"algorithms/histogram_three_bins.ass","name":"histogram","args":[[-1,0,2,3,-4]],"expected":{"negative":2,"zero":1,"positive":2},"inspiration":"fixed-size GROUP BY / histogram; finite data"},
  {"id":"argmax","path":"algorithms/argmax.ass","name":"argmax","args":[[3,8,8,2]],"expected":{"value":8,"index":1,"next":4},"inspiration":"argmax with first-tie semantics; finite data"},
  {"id":"trapezoid-integral","path":"algorithms/trapezoid_integral.ass","name":"integral","args":[[0,1,2,3],1],"expected":4.5,"inspiration":"streaming numerical integration"},
  {"id":"finite-difference","path":"algorithms/finite_difference.ass","name":"differences","args":[[2,5,4,10]],"expected":[3,-1,6],"inspiration":"pairwise iterator state"},
  {"id":"stable-minmax","path":"algorithms/stable_minmax.ass","name":"extrema","args":[[4,-2,7,3]],"expected":{"valid":true,"low":-2,"high":7},"inspiration":"empty-aware aggregate result; finite data"},
  {"id":"saxpy","path":"simd/saxpy.ass","name":"saxpy","args":[[1,2,3],[4,5,6],2],"expected":[6,9,12],"inspiration":"BLAS-style affine vector map, retaining f64"},
  {"id":"squared-distance","path":"simd/squared_distance.ass","name":"distance","args":[[1,2,3],[4,6,3]],"expected":25,"inspiration":"numeric array broadcasting and ordered reduction"},
  {"id":"polynomial-map","path":"simd/polynomial_map.ass","name":"polynomial","args":[[0,1,2]],"expected":[5,14,41],"inspiration":"Horner evaluation over arrays"},
  {"id":"clamped-map","path":"simd/clamped_map.ass","name":"clamp","args":[[-2,-0.5,0,0.5,2]],"expected":[-1,-0.5,0,0.5,1],"inspiration":"elementwise clipping without a predicate","libraries":["../lib/patterns.ass"]},
  {"id":"vector-math","path":"simd/vector_math.ass","name":"transform","args":[[-9,16,25]],"expected":[1.5,2,2.5],"inspiration":"lane-wise math; no f32 narrowing"},
  {"id":"telemetry-monitor","path":"case-studies/telemetry_monitor.ass","name":"analyze","args":[[3,4,0],2],"expected":{"count":3,"rejected":0,"mean":2.3333333333333335,"rms":2.886751345948129,"alerts":2},"inspiration":"telemetry ingestion, validation, aggregation and alerting","kind":"case-study"},
  {"id":"checkout-invoice","path":"case-studies/checkout_invoice.ass","name":"invoice","args":[[10,5],[2,3],0.2,0.1],"expected":{"line_count":2,"subtotal":35,"tax":6.300000000000001,"total":37.8},"inspiration":"checkout pricing with explicit input contracts","kind":"case-study"},
  {"id":"session-analytics","path":"case-studies/session_analytics.ass","name":"session_ids","args":[[0,1,10,11,30],5],"expected":[1,1,2,2,3],"inspiration":"sessionizing an event stream with a causal state machine","kind":"case-study"},
  {"id":"inventory-planner","path":"case-studies/inventory_planner.ass","name":"replenish","args":[[2,5,1],[4,3,10],3,2],"expected":[4,14,0],"inspiration":"inventory replenishment; nonnegative integral unit inputs","kind":"case-study"},
  {"id":"particle-step","path":"case-studies/particle_step.ass","name":"advance","args":[[0,10,20],[2,-2,0],0.5],"expected":{"positions":[1,9,20],"kinetic":4,"particles":3},"inspiration":"simulation update with vector maps and numeric reduction","kind":"case-study"},
  {"id":"text-log-summary","path":"case-studies/text_log_summary.ass","name":"summarize","args":["a1\nb23\n"],"expected":{"bytes":7,"digits":3,"lines":2},"inspiration":"log/text ingestion with UTF-8 and ASCII classification","kind":"case-study"},
];
