// Canonical examples, language-pattern inspirations, and app-like fixtures.
export const expandedCorpus = [
  {id:'shape-polynomial',path:'case-studies/products/polynomial.ass',name:'shape_polynomial',
    args:[[2,3,5],{mass:4,position:{x:2,y:3}}],expected:{mass:49,position:{x:19,y:32}},
    libraries:['../lib/products.ass','../lib/polynomials.ass'],
    inspiration:'numeric shape-derived arithmetic using the same source Horner algorithm',kind:'case-study'},
  {id:'shape-stages',path:'case-studies/products/stages.ass',name:'shape_stages',
    args:[{a:2,b:{c:3,d:4}},1],expected:41,
    inspiration:'type structure elaborates an ordinary function pipeline with dynamic parameters',kind:'case-study'},
  {id:'shape-ranges',path:'case-studies/products/ranges.ass',name:'shape_ranges',
    args:[{a:2,b:{c:3,d:1}}],expected:[0,1,1,2,4,4],
    inspiration:'shape-folded range plans, virtual joins and one continuing scan',kind:'case-study'},
  {id:'source-policy-notation',path:'case-studies/notation/source_policy.ass',name:'source_policy',args:[0.25,0.5,0.125],expected:{allowed:true,score:0.5},kind:'case-study',inspiration:'one policy expression with source-defined Boolean or numeric operators'},
  {id:'notation-polynomial',path:'case-studies/notation/polynomial.ass',name:'polynomial',
    libraries:['../lib/polynomials.ass'],args:[[2,3,5],2],expected:{value:19,derivative:11},
    inspiration:'one source algorithm, lexical arithmetic and staged scalar/dual dictionaries',kind:'case-study'},
  {id:'notation-machine-report',path:'case-studies/notation/machine_report.ass',name:'notation_report',
    libraries:['../lib/reducers.ass','../lib/machines.ass'],args:[[0,8,8,0],0.5],
    expected:{totals:[0,4,10,13],peaks:[0,4,6,6],summary:{left:13,right:6}},
    inspiration:'local serial/product notation with an explicit precedence relation and one shared history',kind:'case-study'},
  {id:'notation-section-scan',path:'case-studies/notation/section_scan.ass',name:'section_scan',
    args:[[1,2,3,4],2],expected:[1,3,9,17],
    inspiration:'source-defined joining retains cut-cover evidence and scan fusion',kind:'case-study'},
  {id:'feedback-quantize',path:'case-studies/feedback/quantize.ass',name:'quantize',
    libraries:['../lib/reducers.ass','../lib/machines.ass','../lib/machine-feedback.ass'],
    args:[Array(8).fill(0.25),1,{left:0,right:0}],expected:{values:[0,1,0,0,0,1,0,0],state:{left:0,right:0}},
    inspiration:'old-state error feedback retains small contributions with two scalar states',kind:'case-study'},
  {id:'feedback-blocks',path:'case-studies/feedback/quantize.ass',name:'quantize_blocks',
    libraries:['../lib/reducers.ass','../lib/machines.ass','../lib/machine-feedback.ass'],
    args:[Array(8).fill(0.25),1,3],expected:[0,1,0,0,1,0,0,1],
    inspiration:'reset a composed feedback circuit per block without segment storage',kind:'case-study'},
  {id:'feedback-tracking',path:'case-studies/feedback/tracking.ass',name:'tracking',
    libraries:['../lib/reducers.ass','../lib/machines.ass','../lib/machine-feedback.ass'],
    args:[[1,1,1,1],0.5,{left:0,right:0}],expected:{values:[0.5,0.75,0.875,0.9375],state:{left:0.0625,right:0.9375}},
    inspiration:'close a reusable numerical pipeline over its previous output',kind:'case-study'},
  {id:'operator-product-solve',path:'case-studies/operators/product_solve.ass',name:'product_solve',
    args:[{left:4,right:18}],expected:{breakdown:false,converged:true,iterations:2,
      recurrenceResidualSquared:3.4820813394521224e-31,residualSquared:1.262177448353619e-29,
      solution:{left:1,right:1.9999999999999998}},libraries:['../lib/operators.ass','../lib/krylov.ass'],
    inspiration:'source product/normal operators and bounded matrix-free conjugate gradients',kind:'case-study'},
  {id:'operator-blocks',path:'case-studies/operators/operator_blocks.ass',name:'operator_blocks',
    args:[[1,2,3,4,5,6,7],3],expected:{local:[4,12,24,16,36,60,28],correction:[3,10,21,12,31,54,21]},
    libraries:['../lib/operators.ass'],
    inspiration:'a captured source operator inside chunk scans and aligned output fusion',kind:'case-study'},
  {id:'clocked-shared-prefix',path:'case-studies/machines/shared_prefix.ass',name:'shared_prefix',
    libraries:['../lib/reducers.ass','../lib/machines.ass'],args:[[0,8,8,0],0.5],
    expected:{totals:[0,4,10,13],peaks:[0,4,6,6],summary:{left:13,right:6}},
    inspiration:'one source-defined stateful prefix before two observers',kind:'case-study'},
  {id:'clocked-channels',path:'case-studies/machines/held_channels.ass',name:'held_channels',
    libraries:['../lib/reducers.ass','../lib/machines.ass'],
    args:[[1,99,3,99],[true,false,true,false],[99,20,99,40],[false,true,false,true]],
    expected:{left:[1,1,4,4],right:[0,20,20,60],state:{left:4,right:60}},
    inspiration:'independently held updates, one input-event clock, no held arrays',kind:'case-study'},
  {id:'clocked-monitor',path:'case-studies/machines/resumable_pipeline.ass',name:'monitor_chunk',
    libraries:['../lib/reducers.ass','../lib/machines.ass'],
    args:[[0,8,8,0,8,0],[false,false,false,false,true,false],{alpha:0.5,low:3,high:6},{left:0,right:false}],
    expected:{means:[0,4,6,3,4,2],alarms:[false,false,true,false,false,false],state:{left:2,right:false}},
    inspiration:'composed smoothing and hysteresis with distinct reset/resume state',kind:'case-study'},
  {id:'clocked-block-cascade',path:'case-studies/machines/block_cascade.ass',name:'block_cascade',
    libraries:['../lib/reducers.ass','../lib/machines.ass'],args:[[1,2,3,4,5,6,7],3],expected:[1,4,10,4,13,28,7],
    inspiration:'reset an entire two-stage source machine in symbolic blocks',kind:'case-study'},
  {id:'core-source-basis',path:'case-studies/core/block_energy.ass',name:'block_energy',
    args:[[1,2,3,4,5,6,7],3],expected:[14,77,49],
    inspiration:'ordinary source prelude atop checked block arrays',kind:'case-study'},
  {id:'chunk-report',path:'case-studies/chunk-scans/block_report.ass',name:'block_report',
    args:[[1,2,3,4,5,6,7],3],expected:{local:[1,3,6,4,9,15,7],totals:[1,3,6,10,15,21,28],state:{local:7,total:28}},
    inspiration:'symbolic blocks, local resets, restored zip alignment and a continuing global scan',kind:'case-study'},
  {id:'chunk-energy',path:'case-studies/chunk-scans/block_energy.ass',name:'block_energy',
    args:[[1,2,3,4,5,6,7],3],expected:[14,77,49],
    inspiration:'per-block summaries without arrays of block data',kind:'case-study'},
  {id:'chunk-center',path:'case-studies/chunk-scans/block_center.ass',name:'block_center',
    args:[[1,2,3,4,5,6,7],3],expected:[-1,0,1,-1,0,1,0],
    inspiration:'a block scan seed computes its mean once, then flattening reuses scalar state',kind:'case-study'},
  {id:'window-smooth',path:'case-studies/windows/smooth.ass',name:'smooth',
    args:[[2,4,8,4,2]],expected:[4.5,6,4.5],libraries:['../lib/windows.ass'],
    inspiration:'read-only overlapping neighborhoods without a window matrix',kind:'case-study'},
  {id:'window-correlate',path:'case-studies/windows/correlate.ass',name:'correlate',
    args:[[1,2,3,4,5],[1,0,-1],1],expected:[-2,-2,-2],libraries:['../lib/windows.ass'],
    inspiration:'source-library window views composed with checked zip and ordered reduction',kind:'case-study'},
  {id:'window-report',path:'case-studies/windows/neighborhood_report.ass',name:'neighborhood_report',
    args:[[2,4,8,4,2]],expected:{slopes:[3,0,-3],totals:[3,3,0],state:{slope:-3,total:0}},libraries:['../lib/windows.ass'],
    inspiration:'overlapping reads, one output domain and a shared causal report',kind:'case-study'},
  {id:'window-origin-report',path:'case-studies/windows/origin_report.ass',name:'origin_report',
    args:[[1,2,3,4,5,6],3,2],expected:{indexes:[0,1],starts:[0,2],totals:[6,12]},libraries:['../lib/windows.ass'],
    inspiration:'window ordinals and source origins from one staged traversal without a positional zip',kind:'case-study'},
  {id:'chunk-block-report',path:'case-studies/chunks/block_report.ass',name:'block_report',
    args:[[10,13,20,18,30],2],expected:{relative:[0,3,0,-2,0],totals:[0,3,3,1,1],state:{value:0,total:1,original:91}},
    inspiration:'arithmetic chunk covers, aligned flattening and continuous scan',kind:'case-study'},
  {id:'chunk-block-exposure',path:'case-studies/chunks/block_exposure.ass',name:'block_exposure',
    args:[[10,13,20,18,30],2],expected:[33,58,30],
    inspiration:'block-local causal scans and folds without a nested buffer',kind:'case-study'},
  {id:'chunk-paired-blocks',path:'case-studies/chunks/paired_blocks.ass',name:'paired_blocks',
    args:[[1,2,3,4,5],[2,3,4,5,6],2],expected:[8,32,30],
    inspiration:'nested checked block pairing and reductions',kind:'case-study'},
  {id:'view-section-report',path:'case-studies/views/section_report.ass',name:'section_report',
    args:[[1,2,3,4],{cut:2,leftGain:10,rightGain:100}],
    expected:{values:[10,20,300,400],totals:[10,30,330,730],state:{value:400,total:730,correction:720}},
    inspiration:'cut-cover reassembly, static zip and a single causal report without intermediate arrays',kind:'case-study'},
  {id:'view-rotate-scan',path:'case-studies/views/rotate_scan.ass',name:'rotate_scan',
    args:[[1,2,3,4],2],expected:[3,7,8,10],
    inspiration:'virtual concatenation and a scan whose state crosses the joined boundary',kind:'case-study'},
  {id:'view-adjacent-deltas',path:'case-studies/views/adjacent_deltas.ass',name:'adjacent_deltas',
    args:[[2,5,4,10]],expected:[3,-1,6],
    inspiration:'overlapping dense views and explicit checked positional pairing',kind:'case-study'},
  {id:'lexicographic-nearest',path:'case-studies/ordering/nearest_ties.ass',name:'nearest_ties',
    args:[[7,3,6,4,7,5],5],expected:[5,4,6,3,7,7],
    inspiration:'explicit distance and tie-breaking priorities in one native tuple key',kind:'case-study'},
  {id:'lexicographic-jobs',path:'case-studies/ordering/schedule_jobs.ass',name:'schedule_jobs',
    args:[[2,1,2,3,2],[9,1,4,8,4]],expected:[3,2,4,0,1],
    inspiration:'descending priority, ascending duration, and stable ties without packed scores',kind:'case-study'},
  {id:'native-nearest',path:'case-studies/ordering/nearest.ass',name:'nearest',
    args:[[7,10,4,7,5],5],expected:[5,4,7,7,10],
    inspiration:'native stable key ordering with bounded invocation scratch',kind:'case-study'},
  {id:'native-ranked-readings',path:'case-studies/ordering/ranked_readings.ass',name:'rank_readings',
    args:[[7,10,4,7,5],5],expected:{values:[5,4,7,7,10],positions:[4,2,0,3,1]},
    inspiration:'strict record materialization, stable provenance data and projected outputs',kind:'case-study'},
  {id:'vertical-threshold',path:'case-studies/vertical/threshold.ass',name:'reach_target',
    args:[[2,3,100],5],expected:{total:5,visited:2,reached:true},
    inspiration:'vertical stopping pipeline and a named local result pattern',kind:'case-study'},
  {id:'vertical-shared-report',path:'case-studies/vertical/shared_report.ass',name:'running_report',
    args:[[1,2,3],{start:0,alert:3}],expected:{values:[1,3,6],alerts:[false,true,true],final:6},
    inspiration:'one causal history, named configuration, multiple materialized results',kind:'case-study'},
  {id:'vertical-paired-error',path:'case-studies/vertical/paired_error.ass',name:'error_summary',
    args:[[2,5,8],[1,5,6]],expected:{count:3,rms:Math.sqrt(5/3),maximum:2},
    inspiration:'checked positional alignment, record-state reduction and a named report',kind:'case-study'},
  {id:'resumable-monitor',path:'case-studies/workflows/monitor.ass',name:'monitor_chunk',
    args:[[0,8,8,0,0],{seen:0,mean:0,alarm:false,raised:0,cleared:0},{alpha:0.5,low:3,high:6}],
    expected:{state:{seen:5,mean:1.5,alarm:false,raised:1,cleared:1},smoothed:[0,4,6,3,1.5],alarms:[false,false,true,false,false]},
    inspiration:'chunk-stable smoothing and hysteresis with explicit checkpoint state',kind:'case-study'},
  {"id":"partial-application","path":"patterns/partial_application.ass","name":"main","args":[7],"expected":17,"inspiration":"ML/Haskell currying"},
  {"id":"function-composition","path":"patterns/function_composition.ass","name":"main","args":[4],"expected":25,"inspiration":"Haskell composition","libraries":["../lib/patterns.ass"]},
  {"id":"nested-products","path":"patterns/nested_products.ass","name":"main","args":[3],"expected":50,"inspiration":"ML destructuring"},
  {"id":"record-lens","path":"patterns/record_lens.ass","name":"main","args":[10],"expected":{"score":15,"active":true},"inspiration":"functional lenses","libraries":["../lib/patterns.ass"]},
  {"id":"option-map","path":"patterns/option_map.ass","name":"main","args":[3,true],"expected":9,"inspiration":"Rust Option / ML Maybe encoded as a record","libraries":["../lib/patterns.ass"]},
  {"id":"result-validation","path":"patterns/result_validation.ass","name":"main","args":[5,2],"expected":{"ok":true,"code":0,"value":250},"inspiration":"Rust Result-style explicit error values","libraries":["../lib/patterns.ass"]},
  {"id":"reader-configuration","path":"patterns/reader_configuration.ass","name":"main","args":[2,3],"expected":49,"inspiration":"Reader-style dependency injection","libraries":["../lib/patterns.ass"]},
  {"id":"strategy-dictionary","path":"patterns/strategy_dictionary.ass","name":"main","args":[[2,3,4]],"expected":{"total":9,"product":24},"inspiration":"typeclass/trait dictionary passing; statically staged"},
  {"id":"predicate-algebra","path":"patterns/predicate_algebra.ass","name":"main","args":[[-2,0,2,9,20]],"expected":2,"inspiration":"composable predicates","libraries":["../lib/patterns.ass"]},
  {"id":"church-choice","path":"patterns/church_choice.ass","name":"main","args":[4],"expected":5,"inspiration":"lambda-calculus Church encodings; static functions"},
  {"id":"church-numeral","path":"patterns/church_numeral.ass","name":"main","args":[1],"expected":7,"inspiration":"Church numeral as staged iteration"},
  {"id":"state-passing","path":"patterns/state_passing.ass","name":"main","args":[10],"expected":{"state":15,"first":10,"second":12},"inspiration":"explicit state-passing style"},
  {"id":"newtype-convention","path":"patterns/newtype_convention.ass","name":"main","args":[4],"expected":{"meters":6},"inspiration":"unit wrappers; structural rather than nominal types"},
  {"id":"complex-numbers","path":"patterns/complex_numbers.ass","name":"main","args":[1],"expected":{"real":-5,"imag":10},"inspiration":"record-based complex arithmetic"},
  {"id":"dual-autodiff","path":"patterns/dual_autodiff.ass","name":"main","args":[3],"expected":{"value":27,"derivative":27},"inspiration":"forward-mode dual-number differentiation"},
  {"id":"matrix-transform","path":"patterns/matrix_transform.ass","name":"main","args":[2],"expected":{"_0":8,"_1":10},"inspiration":"fixed-size matrix products via tuple values"},
  {"id":"bounded-while","path":"patterns/bounded_while.ass","name":"main","args":[10],"expected":{"state":16,"steps":4,"done":true},"inspiration":"while-loop variant with explicit work budget"},
  {"id":"generator-every-other","path":"patterns/generator_every_other.ass","name":"main","args":[[1,2,3,4,5]],"expected":[1,3,5],"inspiration":"generator-style state machine; at most one output per input"},
  {"id":"enumerated-map","path":"patterns/enumerated_map.ass","name":"main","args":[[10,20,30]],"expected":[10,21,32],"inspiration":"Python enumerate / Rust enumerate via checked positional pairing"},
  {"id":"filter-map-pipeline","path":"patterns/filter_map_pipeline.ass","name":"main","args":[[-3,2,4]],"expected":20,"inspiration":"iterator pipelines / SQL WHERE plus aggregate"},
  {"id":"take-while-fold","path":"patterns/take_while_fold.ass","name":"main","args":[[1,2,-1,99]],"expected":{"state":3,"steps":3,"done":true},"inspiration":"take-while aggregate variant; stopping event is visited"},
  {"id":"runtime-contract","path":"patterns/runtime_contract.ass","name":"main","args":[[2,4],2],"expected":[1,2],"inspiration":"design-by-contract with explicit trap"},
  {"id":"lazy-default","path":"patterns/lazy_default.ass","name":"main","args":[[]],"expected":42,"inspiration":"lazy optional/default selection"},
  {"id":"polymorphic-identity","path":"patterns/polymorphic_identity.ass","name":"main","args":[5],"expected":{"number":5,"flag":true,"pair":{"_0":5,"_1":false}},"inspiration":"let-polymorphic reuse","libraries":["../lib/patterns.ass"]},
  {"id":"closure-factory","path":"patterns/closure_factory.ass","name":"main","args":[[1,2,3]],"expected":[5,7,9],"inspiration":"capturing closure factory, erased before runtime"},
  {"id":"record-update","path":"patterns/record_update.ass","name":"main","args":["demo"],"expected":{"name":"demo","score":9,"enabled":true},"inspiration":"immutable record update written explicitly"},
  {"id":"fsm-traffic-light","path":"patterns/fsm_traffic_light.ass","name":"main","args":[[1,1,1,1,1]],"expected":[1,2,0,1,2],"inspiration":"finite state machine with numeric tags"},
  {"id":"histogram-three-bins","path":"algorithms/histogram_three_bins.ass","name":"histogram","args":[[-1,0,2,3,-4]],"expected":{"negative":2,"zero":1,"positive":2},"inspiration":"fixed-size GROUP BY / histogram; finite data"},
  {"id":"argmax","path":"algorithms/argmax.ass","name":"argmax","args":[[3,8,8,2]],"expected":{"value":8,"index":1,"next":4},"inspiration":"argmax with first-tie semantics; finite data"},
  {"id":"trapezoid-integral","path":"algorithms/trapezoid_integral.ass","name":"integral","args":[[0,1,2,3],1],"expected":4.5,"inspiration":"streaming numerical integration"},
  {"id":"finite-difference","path":"algorithms/finite_difference.ass","name":"differences","args":[[2,5,4,10]],"expected":[3,-1,6],"inspiration":"pairwise iterator state"},
  {"id":"stable-minmax","path":"algorithms/stable_minmax.ass","name":"extrema","args":[[4,-2,7,3]],"expected":{"valid":true,"low":-2,"high":7},"inspiration":"empty-aware aggregate result; finite data"},
  {"id":"saxpy","path":"simd/saxpy.ass","name":"saxpy","args":[[1,2,3],[4,5,6],2],"expected":[6,9,12],"inspiration":"BLAS-style affine vector map, retaining f64"},
  {"id":"squared-distance","path":"simd/squared_distance.ass","name":"distance","args":[[1,2,3],[4,6,3]],"expected":25,"inspiration":"numeric array broadcasting and ordered reduction"},
  {"id":"polynomial-map","path":"simd/polynomial_map.ass","name":"polynomial","args":[[0,1,2]],"expected":[5,14,41],"inspiration":"Horner evaluation over arrays"},
  {"id":"clamped-map","path":"simd/clamped_map.ass","name":"clamp","args":[[-2,-0.5,0,0.5,2]],"expected":[-1,-0.5,0,0.5,1],"inspiration":"elementwise clipping without a predicate","libraries":["../lib/patterns.ass"]},
  {"id":"vector-math","path":"simd/vector_math.ass","name":"transform","args":[[-9,16,25]],"expected":[1.5,2,2.5],"inspiration":"lane-wise math; no f32 narrowing"},
  {"id":"telemetry-monitor","path":"case-studies/telemetry_monitor.ass","name":"analyze","args":[[3,4,0],2],"expected":{"count":3,"rejected":0,"mean":2.3333333333333335,"rms":2.886751345948129,"alerts":2},"inspiration":"telemetry ingestion, validation, aggregation and alerting","kind":"case-study"},
  {"id":"checkout-invoice","path":"case-studies/checkout_invoice.ass","name":"invoice","args":[[10,5],[2,3],0.2,0.1],"expected":{"line_count":2,"subtotal":35,"tax":6.300000000000001,"total":37.8},"inspiration":"checkout pricing with explicit input contracts","kind":"case-study"},
  {"id":"session-analytics","path":"case-studies/session_analytics.ass","name":"session_ids","args":[[0,1,10,11,30],5],"expected":[1,1,2,2,3],"inspiration":"sessionizing an event stream with a causal state machine","kind":"case-study"},
  {"id":"inventory-planner","path":"case-studies/inventory_planner.ass","name":"replenish","args":[[2,5,1],[4,3,10],3,2],"expected":[4,14,0],"inspiration":"inventory replenishment; nonnegative integral unit inputs","kind":"case-study"},
  {"id":"particle-step","path":"case-studies/particle_step.ass","name":"advance","args":[[0,10,20],[2,-2,0],0.5],"expected":{"positions":[1,9,20],"kinetic":4,"particles":3},"inspiration":"simulation update with vector maps and numeric reduction","kind":"case-study"},
  {"id":"text-log-summary","path":"case-studies/text_log_summary.ass","name":"summarize","args":["a1\nb23\n"],"expected":{"bytes":7,"digits":3,"lines":2},"inspiration":"log/text ingestion with UTF-8 and ASCII classification","kind":"case-study"},
];
