import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { parse, infer, primitiveArities } from '../src/frontend.mjs';

// Deterministic packaging only: compiler execution never reads the filesystem.
const args = process.argv.slice(2);
if (args.length > 1 || args.length && args[0] !== '--check')
  throw new TypeError('Usage: node scripts/build-prelude.mjs [--check]');
const source = await readFile(new URL('../lib/prelude.ass', import.meta.url), 'utf8');
const program = parse(source);
assert.equal(program.hosts.length, 0, 'The shipped prelude cannot declare host authority');
assert.equal(program.symbols.length, 0, 'The shipped prelude needs no global symbol keys');
infer(program, {prelude:false}); // All definitions must type-check over primitives alone.
const arities = {};
for (const d of program.definitions) {
  assert(!d.exported && d.syntax === 'unary', 'Prelude definitions are private canonical source');
  assert(!Object.hasOwn(primitiveArities,d.name), `Prelude shadows primitive ${d.name}`);
  arities[d.name] = d.params.length;
}
const generated = '// Generated by scripts/build-prelude.mjs from lib/prelude.ass. Do not edit.\n'
  + `export const preludeSource = ${JSON.stringify(source)};\n`
  + `export const preludeArities = Object.freeze(${JSON.stringify(arities)});\n`;
const destination = new URL('../src/prelude-source.mjs', import.meta.url);
if (args[0] === '--check') {
  assert.equal(await readFile(destination,'utf8'),generated,'Stale prelude snapshot: run npm run build:prelude');
  console.log('Source prelude snapshot matches.');
} else {
  await writeFile(destination,generated);
  console.log('Updated src/prelude-source.mjs from ordinary Asslang source.');
}
